### PR TITLE
Supporting users other than 'clear', we will run into this issue in t…

### PR DESCRIPTION
**Pull request by NitinAtIntel**
…he event that someone is using libvirt on a host machine running Clear Linux

### CODE REVIEW

**Review by knangia — COMMENTED** [review]
correct, it works with $USER, for machines having usernames other than clear, else will have to replace "clear" with username every time.

**Comment by NitinAtIntel** [comment]
Hi @AntonioMeireles, what do you think? To clarify, @knangia is attempting to leverage this script to get vagrant with libvirt up and running on a clear *host*.  Therefore, the user will not necessarily be 'clear'.

**Comment by AntonioMeireles** [comment]
looks good - at sight forward and backward compatible :-) 

&& *THANKS*! ...

**Comment by knangia** [comment]
Thank you! 😊

**Pull request merged**
